a=int(input("Enter the value of a\n"))
b=int(input("Enter the value of b\n"))
print("addition of {0} and {1} is {2}".format(a,b,a+b))
print("multipliction  of {0} and {1} is {2} ".format(a,b,a*b))
print("division   of {0} and {1} is {2}".format(a,b,a/b))
print('substraction of {0} - {1} ={2} '.format(a,b,a-b))